class Debug:
    def __init__(self, uber):
        self.previous_unprocessed_requests = uber.unprocessed_requests.copy()
        self.previous_pending_requests = uber.pending_requests.copy()
        self.previous_pickup_rides = uber.pickup_rides.copy()
        self.previous_onroad_rides = uber.onroad_rides.copy()
        self.previous_ended_rides = uber.ended_rides.copy()
        self.previous_canceled_rides = uber.canceled_rides.copy()
        self.previous_idle_drivers = uber.idle_drivers.copy()
        self.previous_pickup_drivers = uber.pickup_drivers.copy()
        self.previous_onroad_drivers = uber.onroad_drivers.copy()
        self.previous_inactive_drivers = uber.inactive_drivers.copy()
        self.previous_matched_rides = uber.matched_rides.copy()
        pass

    def print_state(self, timestamp,uber,reservations=[]):
        print("DEBUG - STATE")
        print(f"Timestamp: {timestamp}")
        if (len(reservations) > 0):
            print("-"*15)
            print("NEW RESERVATIONS")
            print("-"*15)
            for p in reservations:
                print(f"{p.id} - {p.persons[0]} - {p}")
        print("-"*13)
        print("\nMATCHED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_matched_rides()
        print("-"*13)
        print("\nUNPROCESSED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.unprocessed_requests)
        print("-"*13)
        print("\nPICKUP RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.pickup_rides)
        print("-"*13)
        print("-"*13)
        print("\nONROAD RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.onroad_rides)
        print("-"*13)
        print("\nENDED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.ended_rides)
        print("-"*13)
        print("\nCANCELED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.canceled_rides)
        print("-"*13)
        print("\nIDLE DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.idle_drivers)
        print("-"*13)
        print("\nPICKUP DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.pickup_drivers)
        print("-"*13)
        print("\nONROAD DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.onroad_drivers)
        print("-"*13)
        print("\nINACTIVE DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(uber.inactive_drivers)
        print("-"*13)
        print("\nPREVIOUS STATE\n")
        print("-"*13)
        print("\n")
        print("-"*13)
        print("\nMATCHED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_matched_rides()
        print("-"*13)
        print("\nUNPROCESSED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_unprocessed_requests)
        print("-"*13)
        print("\nPICKUP RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_pickup_rides)
        print("-"*13)
        print("-"*13)
        print("\nONROAD RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_onroad_rides)
        print("-"*13)
        print("\nENDED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_ended_rides)
        print("-"*13)
        print("\nCANCELED RIDEs\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_canceled_rides)
        print("-"*13)
        print("\nIDLE DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_idle_drivers)
        print("-"*13)
        print("\nPICKUP DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_pickup_drivers)
        print("-"*13)
        print("\nONROAD DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_onroad_drivers)
        print("-"*13)
        print("\nINACTIVE DRIVERS\n")
        print("-"*13)
        print("\n")
        uber.print_ride_list(self.previous_inactive_drivers)
    

    def save_state(self, uber):
        self.previous_unprocessed_requests = uber.unprocessed_requests.copy()
        self.previous_pending_requests = uber.pending_requests.copy()
        self.previous_pickup_rides = uber.pickup_rides.copy()
        self.previous_onroad_rides = uber.onroad_rides.copy()
        self.previous_ended_rides = uber.ended_rides.copy()
        self.previous_canceled_rides = uber.canceled_rides.copy()
        self.previous_idle_drivers = uber.idle_drivers.copy()
        self.previous_pickup_drivers = uber.pickup_drivers.copy()
        self.previous_onroad_drivers = uber.onroad_drivers.copy()
        self.previous_inactive_drivers = uber.inactive_drivers.copy()
        self.previous_matched_rides = uber.matched_rides.copy()
