from enum import Enum

class EventType(str, Enum):
    GENERATION_POLICY = "GENERATION_POLICY"
    HUMAN_PERSONALITY_POLICY = "HUMAN_PERSONALITY_POLICY"
    GENERATE_TRAFFIC = "GENERATE_TRAFFIC"
    DRIVERS_STRIKE = "DRIVERS_STRIKE"
    INCREASE_LENGTH_RIDES = "INCREASE_LENGTH_RIDES"
    BLOCK_STREETS = "BLOCK_STREETS"
    SLOW_DOWN_SPEED = "SLOW_DOWN_SPEED"
